framework:
 DATASET: "/tmpdir/lavinas/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 OUTPUT: /tmpdir/lavinas//results_trad
 save_results: /tmpdir/lavinas/results_trad

variables:
 generations: 1
 _lambda: 5
 frequency: 100
 n_models: 1
 iter: 2000
 indices: None
