framework:
 DATASET: "/tmpdir/lavinas/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 OUTPUT: /tmpdir/lavinas/results_roulette_inc_del_02_mutkartezio_t01
 save_results: /tmpdir/lavinas/results_roulette_inc_del_02_mutkartezio_t01

variables:
 generations: 1
 _lambda: 5
 frequency: 100
 n_models: 1
 iter: 2192
 indices: None
 method: roulette_inc_del
 c: 2
 a: 0.5 
 t: 0.05
 restart: False
 val: 15000000000000000

