framework:
 DATASET: "/tmpdir/lavinas/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 OUTPUT: /tmpdir/lavinas/results_roulette_inc_del_02_mutkartezio_t01_random
 save_results: /tmpdir/lavinas/results_roulette_inc_del_02_mutkartezio_t01_random

variables:
 generations: 1
 _lambda: 5
 frequency: 100
 n_models: 1
 maxeval: 60000
 indices: None
 method: random
 c: 2
 a: 0.5 
 t_easy: 0
 t_hard: 1
 restart: True
 val: 6000


