framework:
 DATASET_ssi: "../datasets/cellpose"
 filename: dataset.csv
 filename_test: dataset_test.csv
 filename_train: dataset_train.csv
 meta_filename: META_rgb.json
 OUTPUT: results
 save_results: results

variables:
 endpoint: EndpointThreshold
 threshold: 128
 generations: 500
 _lambda: 5
 frequency: 100000
 n_models: 10
 user_t: 0.00
 img_t: 0.00
 ask_user: False
 verbose: True
 al_iter: 8
 method: disagreement
 indices: [2, 52, 29, 1, 40, 28, 19, 79]