framework:
 DATASET: "/tmpdir/lavinas/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 OUTPUT: /tmpdir/lavinas/results_roulette_inc_del_02_mutkartezio_t01_restart
 save_results: /tmpdir/lavinas/results_roulette_inc_del_02_mutkartezio_t01_restart

variables:
 generations: 1
 _lambda: 5
 frequency: 100
 n_models: 1
 iter: 5022
 indices: None
 method: roulette_inc_del
 c: 2
 a: 0.5 
 t: 0.1
 restart: True
 val: 15000

