framework:
 DATASET: "/Users/yurilavinas/Downloads/datasets/processed/Breast"
 filename: dataset.csv
 meta_filename: META.json
 save_results: results/cluster/

variables:
 generations: 100
 _lambda: 4
 frequency: 50
 total_images: 1659
 maxeval: 10000000
 indices: None
 method: uncertainty_weighted
 n_future: 99
 n_noise: 5
 n_diverse: 165
 init_idx: cluster 
 img_limit: 165
 diverseSET: True