
framework:
 DATASET: "/tmpdir/p21049ly/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: /tmpdir/p21049ly/al_cgp_gen_1_nmodels_1_10

variables:
 generations: 1
 _lambda: 5
 frequency: 100
 n_models: 1
 maxeval: 1000000
 indices: 10
 method: none


 