framework:
 DATASET: "/tmpdir/lavinas/datasets/cellpose/"
 filename: dataset.csv
 meta_filename: META.json
 save_results: /tmpdir/lavinas/results/ppsn_like/

variables:
 generations: 100
 _lambda: 4
 frequency: 50
 n_mutations: 1
 maxeval: 1000000
 indices: None
 method: rnd
 n_future: 14
 n_noise: 5
 n_diverse: -99999999999
 init_idx: rnd 
 img_limit: 10
 diverseSET: False