
framework:
 DATASET: "/tmpdir/p21049ly/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: /tmpdir/p21049ly/al_uncertainty_weighted_gen_100_nmodels_15_norep

variables:
 generations: 100
 _lambda: 10
 frequency: 100
 n_models: 15
 maxeval: 400000  
 indices: None
 method: uncertainty_weighted
