
framework:
 DATASET: "/tmpdir/p21049ly/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: /tmpdir/p21049ly/al_random_gen_10_nmodels_5

variables:
 generations: 10
 _lambda: 5
 frequency: 100
 n_models: 5
 maxeval: 150000
 indices: None
 method: random
