framework:
 DATASET: "/tmpdir/lavinas/datasets/cellpose/"
 filename: dataset.csv
 meta_filename: META.json
 save_results: /tmpdir/lavinas/results/cluster/

variables:
 generations: 100
 _lambda: 4
 frequency: 50
 n_mutations: 1
 maxeval: 1000000
 indices: None
 method: uncertainty_weighted
 n_future: 99
 n_noise: 100
 n_diverse: 10
 init_idx: cluster 
 img_limit: 10
 diverseSET: True