
framework:
 DATASET: "/tmpdir/lavinas/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: /tmpdir/lavinas/al_random_gen_100_nmodels_1

variables:
 generations: 100
 _lambda: 10
 frequency: 100
 n_models: 1
 maxeval: 150000
 indices: None
 method: random
