
framework:
 DATASET: "/tmpdir/lavinas/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: /tmpdir/lavinas/al_uncertainty_gen_10_nmodels_2

variables:
 generations: 100
 _lambda: 10
 frequency: 100
 n_models: 2
 maxeval: 150000
 indices: None
 method: uncertainty
