
framework:
 DATASET: "/tmpdir/p21049ly/cellpose"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: /tmpdir/p21049ly/al_cgp_gen_100_nmodels_1

variables:
 generations: 100
 _lambda: 5
 frequency: 100
 n_models: 1
 maxeval: 200000
 indices: None
 method: none
