
framework:
 DATASET: "../datasets/lymphoma"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: ../tmp_10

variables:
 generations: 100
 _lambda: 5
 frequency: 100
 n_models: 1
 maxeval: 20000000
 indices: [53, 7, 69, 33, 9, 75, 0, 74, 27, 64, 37]
 method: none
