
framework:
 DATASET: "../datasets/lymphoma"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: ../tmp_m

variables:
 generations: 100
 _lambda: 5
 frequency: 100
 n_models: 1
 maxeval: 20000000
 indices: [0,5,7,12,20,80,81,82,83,84]
 method: none
