
framework:
 DATASET: "../datasets/lymphoma"
 filename: dataset.csv
 meta_filename: META_rgb.json
 save_results: ../tmp_10

variables:
 generations: 1
 _lambda: 5
 frequency: 100
 n_models: 1
 maxeval: 20000000
 indices: none
 method: none
